# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0004_auto_20181023_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
