# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0005_neighbourhood_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
