# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0009_auto_20181021_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.Profile'),
        ),
    ]
