# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0011_auto_20181021_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='health_department',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='health_department_address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='police_department',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='police_department_address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
