# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0012_auto_20181021_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='hospital_call_number',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='hospital_email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='police_call_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='police_email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
