# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0019_auto_20181022_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='neighbourhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.Neighbourhood'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='neighbourhood',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.Neighbourhood'),
        ),
    ]
