# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0021_auto_20181022_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='Neighbourhood_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.Neighbourhood'),
            preserve_default=False,
        ),
    ]
