# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0023_auto_20181022_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='neighbourhood',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.Neighbourhood'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='Neighbourhood_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='neighbourhood',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.Neighbourhood'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.Neighbourhood'),
            preserve_default=False,
        ),
    ]
